export type WorldCountry = {
  code: string;
  name: string;
  flag: string;
  phone_code: string;
  currency: string;
  localities: string[];
};

export const WORLD_COUNTRIES: WorldCountry[] = [
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', phone_code: '+93', currency: 'AFN', localities: ['Kabul', 'Herat', 'Mazar-i-Sharif', 'Kandahar'] },
  { code: 'AL', name: 'Albania', flag: '🇦🇱', phone_code: '+355', currency: 'ALL', localities: ['Tirana', 'Durres', 'Vlore', 'Shkoder'] },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿', phone_code: '+213', currency: 'DZD', localities: ['Algiers', 'Oran', 'Constantine', 'Annaba'] },
  { code: 'AD', name: 'Andorra', flag: '🇦🇩', phone_code: '+376', currency: 'EUR', localities: ['Andorra la Vella', 'Escaldes-Engordany'] },
  { code: 'AO', name: 'Angola', flag: '🇦🇴', phone_code: '+244', currency: 'AOA', localities: ['Luanda', 'Huambo', 'Lobito', 'Benguela'] },
  { code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬', phone_code: '+1-268', currency: 'XCD', localities: ['St. John\'s', 'All Saints'] },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷', phone_code: '+54', currency: 'ARS', localities: ['Buenos Aires', 'Cordoba', 'Rosario', 'Mendoza'] },
  { code: 'AM', name: 'Armenia', flag: '🇦🇲', phone_code: '+374', currency: 'AMD', localities: ['Yerevan', 'Gyumri', 'Vanadzor'] },
  { code: 'AU', name: 'Australia', flag: '🇦🇺', phone_code: '+61', currency: 'AUD', localities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide'] },
  { code: 'AT', name: 'Austria', flag: '🇦🇹', phone_code: '+43', currency: 'EUR', localities: ['Vienna', 'Salzburg', 'Graz', 'Linz', 'Innsbruck'] },
  { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿', phone_code: '+994', currency: 'AZN', localities: ['Baku', 'Ganja', 'Sumqayit'] },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸', phone_code: '+1-242', currency: 'BSD', localities: ['Nassau', 'Freeport'] },
  { code: 'BH', name: 'Bahrain', flag: '🇧🇭', phone_code: '+973', currency: 'BHD', localities: ['Manama', 'Riffa', 'Muharraq'] },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', phone_code: '+880', currency: 'BDT', localities: ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi'] },
  { code: 'BB', name: 'Barbados', flag: '🇧🇧', phone_code: '+1-246', currency: 'BBD', localities: ['Bridgetown', 'Speightstown'] },
  { code: 'BY', name: 'Belarus', flag: '🇧🇾', phone_code: '+375', currency: 'BYN', localities: ['Minsk', 'Gomel', 'Mogilev'] },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪', phone_code: '+32', currency: 'EUR', localities: ['Brussels', 'Antwerp', 'Ghent', 'Charleroi'] },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿', phone_code: '+501', currency: 'BZD', localities: ['Belize City', 'Belmopan'] },
  { code: 'BJ', name: 'Benin', flag: '🇧🇯', phone_code: '+229', currency: 'XOF', localities: ['Cotonou', 'Porto-Novo', 'Parakou', 'Djougou'] },
  { code: 'BT', name: 'Bhutan', flag: '🇧🇹', phone_code: '+975', currency: 'BTN', localities: ['Thimphu', 'Phuntsholing'] },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴', phone_code: '+591', currency: 'BOB', localities: ['La Paz', 'Sucre', 'Santa Cruz', 'Cochabamba'] },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦', phone_code: '+387', currency: 'BAM', localities: ['Sarajevo', 'Banja Luka', 'Tuzla'] },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼', phone_code: '+267', currency: 'BWP', localities: ['Gaborone', 'Francistown', 'Maun'] },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷', phone_code: '+55', currency: 'BRL', localities: ['Sao Paulo', 'Rio de Janeiro', 'Brasilia', 'Salvador'] },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳', phone_code: '+673', currency: 'BND', localities: ['Bandar Seri Begawan', 'Kuala Belait'] },
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬', phone_code: '+359', currency: 'BGN', localities: ['Sofia', 'Plovdiv', 'Varna'] },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', phone_code: '+226', currency: 'XOF', localities: ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou'] },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮', phone_code: '+257', currency: 'BIF', localities: ['Gitega', 'Bujumbura', 'Muyinga'] },
  { code: 'KH', name: 'Cambodia', flag: '🇰🇭', phone_code: '+855', currency: 'KHR', localities: ['Phnom Penh', 'Siem Reap', 'Battambang'] },
  { code: 'CM', name: 'Cameroon', flag: '🇨🇲', phone_code: '+237', currency: 'XAF', localities: ['Douala', 'Yaoundé', 'Garoua', 'Bamenda'] },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', phone_code: '+1', currency: 'CAD', localities: ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Ottawa'] },
  { code: 'CV', name: 'Cape Verde', flag: '🇨🇻', phone_code: '+238', currency: 'CVE', localities: ['Praia', 'Mindelo', 'Espargos'] },
  { code: 'CF', name: 'Central African Republic', flag: '🇨🇫', phone_code: '+236', currency: 'XAF', localities: ['Bangui', 'Bimbo', 'Mbaiki'] },
  { code: 'TD', name: 'Chad', flag: '🇹🇩', phone_code: '+235', currency: 'XAF', localities: ['N\'Djamena', 'Moundou', 'Sarh'] },
  { code: 'CL', name: 'Chile', flag: '🇨🇱', phone_code: '+56', currency: 'CLP', localities: ['Santiago', 'Valparaiso', 'Concepcion'] },
  { code: 'CN', name: 'China', flag: '🇨🇳', phone_code: '+86', currency: 'CNY', localities: ['Beijing', 'Shanghai', 'Shenzhen', 'Guangzhou', 'Chengdu'] },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴', phone_code: '+57', currency: 'COP', localities: ['Bogota', 'Medellin', 'Cali', 'Barranquilla'] },
  { code: 'KM', name: 'Comoros', flag: '🇰🇲', phone_code: '+269', currency: 'KMF', localities: ['Moroni', 'Mutsamudu', 'Fomboni'] },
  { code: 'CG', name: 'Congo (Republic)', flag: '🇨🇬', phone_code: '+242', currency: 'XAF', localities: ['Brazzaville', 'Pointe-Noire', 'Dolisie'] },
  { code: 'CD', name: 'Congo (DRC)', flag: '🇨🇩', phone_code: '+243', currency: 'CDF', localities: ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Goma'] },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', phone_code: '+506', currency: 'CRC', localities: ['San Jose', 'Alajuela', 'Cartago'] },
  { code: 'HR', name: 'Croatia', flag: '🇭🇷', phone_code: '+385', currency: 'EUR', localities: ['Zagreb', 'Split', 'Rijeka'] },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺', phone_code: '+53', currency: 'CUP', localities: ['Havana', 'Santiago de Cuba', 'Camaguey'] },
  { code: 'CY', name: 'Cyprus', flag: '🇨🇾', phone_code: '+357', currency: 'EUR', localities: ['Nicosia', 'Limassol', 'Larnaca'] },
  { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿', phone_code: '+420', currency: 'CZK', localities: ['Prague', 'Brno', 'Ostrava'] },
  { code: 'CI', name: 'Côte d\'Ivoire', flag: '🇨🇮', phone_code: '+225', currency: 'XOF', localities: ['Abidjan', 'Bouaké', 'Yamoussoukro', 'San-Pédro', 'Korhogo'] },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰', phone_code: '+45', currency: 'DKK', localities: ['Copenhagen', 'Aarhus', 'Odense'] },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯', phone_code: '+253', currency: 'DJF', localities: ['Djibouti', 'Ali Sabieh', 'Tadjoura'] },
  { code: 'DM', name: 'Dominica', flag: '🇩🇲', phone_code: '+1-767', currency: 'XCD', localities: ['Roseau', 'Portsmouth'] },
  { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴', phone_code: '+1-809', currency: 'DOP', localities: ['Santo Domingo', 'Santiago'] },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨', phone_code: '+593', currency: 'USD', localities: ['Quito', 'Guayaquil', 'Cuenca'] },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬', phone_code: '+20', currency: 'EGP', localities: ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said'] },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻', phone_code: '+503', currency: 'USD', localities: ['San Salvador', 'Santa Ana'] },
  { code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶', phone_code: '+240', currency: 'XAF', localities: ['Malabo', 'Bata', 'Ebebiyin'] },
  { code: 'ER', name: 'Eritrea', flag: '🇪🇷', phone_code: '+291', currency: 'ERN', localities: ['Asmara', 'Keren', 'Massawa'] },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪', phone_code: '+372', currency: 'EUR', localities: ['Tallinn', 'Tartu', 'Narva'] },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿', phone_code: '+268', currency: 'SZL', localities: ['Mbabane', 'Manzini'] },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹', phone_code: '+251', currency: 'ETB', localities: ['Addis Ababa', 'Dire Dawa', 'Mekele', 'Gondar'] },
  { code: 'FJ', name: 'Fiji', flag: '🇫🇯', phone_code: '+679', currency: 'FJD', localities: ['Suva', 'Lautoka', 'Nadi'] },
  { code: 'FI', name: 'Finland', flag: '🇫🇮', phone_code: '+358', currency: 'EUR', localities: ['Helsinki', 'Espoo', 'Tampere'] },
  { code: 'FR', name: 'France', flag: '🇫🇷', phone_code: '+33', currency: 'EUR', localities: ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice'] },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦', phone_code: '+241', currency: 'XAF', localities: ['Libreville', 'Port-Gentil', 'Franceville'] },
  { code: 'GM', name: 'Gambia', flag: '🇬🇲', phone_code: '+220', currency: 'GMD', localities: ['Banjul', 'Serekunda', 'Brikama'] },
  { code: 'GE', name: 'Georgia', flag: '🇬🇪', phone_code: '+995', currency: 'GEL', localities: ['Tbilisi', 'Kutaisi', 'Batumi'] },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', phone_code: '+49', currency: 'EUR', localities: ['Berlin', 'Munich', 'Frankfurt', 'Hamburg', 'Cologne'] },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', phone_code: '+233', currency: 'GHS', localities: ['Accra', 'Kumasi', 'Tamale', 'Takoradi'] },
  { code: 'GR', name: 'Greece', flag: '🇬🇷', phone_code: '+30', currency: 'EUR', localities: ['Athens', 'Thessaloniki', 'Patras'] },
  { code: 'GD', name: 'Grenada', flag: '🇬🇩', phone_code: '+1-473', currency: 'XCD', localities: ['St. George\'s', 'Gouyave'] },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹', phone_code: '+502', currency: 'GTQ', localities: ['Guatemala City', 'Mixco', 'Quetzaltenango'] },
  { code: 'GN', name: 'Guinea', flag: '🇬🇳', phone_code: '+224', currency: 'GNF', localities: ['Conakry', 'Nzerekore', 'Kankan', 'Kindia'] },
  { code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼', phone_code: '+245', currency: 'XOF', localities: ['Bissau', 'Bafata', 'Gabú'] },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾', phone_code: '+592', currency: 'GYD', localities: ['Georgetown', 'Linden'] },
  { code: 'HT', name: 'Haiti', flag: '🇭🇹', phone_code: '+509', currency: 'HTG', localities: ['Port-au-Prince', 'Carrefour', 'Delmas'] },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳', phone_code: '+504', currency: 'HNL', localities: ['Tegucigalpa', 'San Pedro Sula'] },
  { code: 'HU', name: 'Hungary', flag: '🇭🇺', phone_code: '+36', currency: 'HUF', localities: ['Budapest', 'Debrecen', 'Szeged'] },
  { code: 'IS', name: 'Iceland', flag: '🇮🇸', phone_code: '+354', currency: 'ISK', localities: ['Reykjavik', 'Kopavogur'] },
  { code: 'IN', name: 'India', flag: '🇮🇳', phone_code: '+91', currency: 'INR', localities: ['Mumbai', 'Delhi', 'Bangalore', 'Kolkata', 'Chennai'] },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩', phone_code: '+62', currency: 'IDR', localities: ['Jakarta', 'Surabaya', 'Bandung', 'Medan'] },
  { code: 'IR', name: 'Iran', flag: '🇮🇷', phone_code: '+98', currency: 'IRR', localities: ['Tehran', 'Mashhad', 'Isfahan'] },
  { code: 'IQ', name: 'Iraq', flag: '🇮🇶', phone_code: '+964', currency: 'IQD', localities: ['Baghdad', 'Basra', 'Mosul'] },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪', phone_code: '+353', currency: 'EUR', localities: ['Dublin', 'Cork', 'Limerick'] },
  { code: 'IL', name: 'Israel', flag: '🇮🇱', phone_code: '+972', currency: 'ILS', localities: ['Jerusalem', 'Tel Aviv', 'Haifa'] },
  { code: 'IT', name: 'Italy', flag: '🇮🇹', phone_code: '+39', currency: 'EUR', localities: ['Rome', 'Milan', 'Naples', 'Turin', 'Florence'] },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲', phone_code: '+1-876', currency: 'JMD', localities: ['Kingston', 'Montego Bay'] },
  { code: 'JP', name: 'Japan', flag: '🇯🇵', phone_code: '+81', currency: 'JPY', localities: ['Tokyo', 'Osaka', 'Kyoto', 'Yokohama', 'Nagoya'] },
  { code: 'JO', name: 'Jordan', flag: '🇯🇴', phone_code: '+962', currency: 'JOD', localities: ['Amman', 'Zarqa', 'Irbid'] },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', phone_code: '+7', currency: 'KZT', localities: ['Almaty', 'Nur-Sultan', 'Shymkent'] },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', phone_code: '+254', currency: 'KES', localities: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret'] },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮', phone_code: '+686', currency: 'AUD', localities: ['Tarawa', 'Betio'] },
  { code: 'KP', name: 'North Korea', flag: '🇰🇵', phone_code: '+850', currency: 'KPW', localities: ['Pyongyang', 'Hamhung'] },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷', phone_code: '+82', currency: 'KRW', localities: ['Seoul', 'Busan', 'Incheon'] },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼', phone_code: '+965', currency: 'KWD', localities: ['Kuwait City', 'Al Ahmadi'] },
  { code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬', phone_code: '+996', currency: 'KGS', localities: ['Bishkek', 'Osh'] },
  { code: 'LA', name: 'Laos', flag: '🇱🇦', phone_code: '+856', currency: 'LAK', localities: ['Vientiane', 'Pakse'] },
  { code: 'LV', name: 'Latvia', flag: '🇱🇻', phone_code: '+371', currency: 'EUR', localities: ['Riga', 'Daugavpils'] },
  { code: 'LB', name: 'Lebanon', flag: '🇱🇧', phone_code: '+961', currency: 'LBP', localities: ['Beirut', 'Tripoli', 'Sidon'] },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸', phone_code: '+266', currency: 'LSL', localities: ['Maseru', 'Teyateyaneng'] },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷', phone_code: '+231', currency: 'LRD', localities: ['Monrovia', 'Gbarnga', 'Kakata'] },
  { code: 'LY', name: 'Libya', flag: '🇱🇾', phone_code: '+218', currency: 'LYD', localities: ['Tripoli', 'Benghazi', 'Misrata'] },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮', phone_code: '+423', currency: 'CHF', localities: ['Vaduz', 'Schaan'] },
  { code: 'LT', name: 'Lithuania', flag: '🇱🇹', phone_code: '+370', currency: 'EUR', localities: ['Vilnius', 'Kaunas'] },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', phone_code: '+352', currency: 'EUR', localities: ['Luxembourg City', 'Esch-sur-Alzette'] },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬', phone_code: '+261', currency: 'MGA', localities: ['Antananarivo', 'Toamasina', 'Antsirabe'] },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼', phone_code: '+265', currency: 'MWK', localities: ['Lilongwe', 'Blantyre', 'Mzuzu'] },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾', phone_code: '+60', currency: 'MYR', localities: ['Kuala Lumpur', 'Penang', 'Johor Bahru'] },
  { code: 'MV', name: 'Maldives', flag: '🇲🇻', phone_code: '+960', currency: 'MVR', localities: ['Male', 'Addu City'] },
  { code: 'ML', name: 'Mali', flag: '🇲🇱', phone_code: '+223', currency: 'XOF', localities: ['Bamako', 'Sikasso', 'Mopti', 'Kayes'] },
  { code: 'MT', name: 'Malta', flag: '🇲🇹', phone_code: '+356', currency: 'EUR', localities: ['Valletta', 'Birkirkara'] },
  { code: 'MH', name: 'Marshall Islands', flag: '🇲🇭', phone_code: '+692', currency: 'USD', localities: ['Majuro', 'Ebeye'] },
  { code: 'MR', name: 'Mauritania', flag: '🇲🇷', phone_code: '+222', currency: 'MRU', localities: ['Nouakchott', 'Nouadhibou', 'Néma'] },
  { code: 'MU', name: 'Mauritius', flag: '🇲🇺', phone_code: '+230', currency: 'MUR', localities: ['Port Louis', 'Beau Bassin'] },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽', phone_code: '+52', currency: 'MXN', localities: ['Mexico City', 'Guadalajara', 'Monterrey'] },
  { code: 'FM', name: 'Micronesia', flag: '🇫🇲', phone_code: '+691', currency: 'USD', localities: ['Palikir', 'Weno'] },
  { code: 'MD', name: 'Moldova', flag: '🇲🇩', phone_code: '+373', currency: 'MDL', localities: ['Chisinau', 'Balti'] },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨', phone_code: '+377', currency: 'EUR', localities: ['Monaco', 'Monte Carlo'] },
  { code: 'MN', name: 'Mongolia', flag: '🇲🇳', phone_code: '+976', currency: 'MNT', localities: ['Ulaanbaatar', 'Erdenet'] },
  { code: 'ME', name: 'Montenegro', flag: '🇲🇪', phone_code: '+382', currency: 'EUR', localities: ['Podgorica', 'Niksic'] },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦', phone_code: '+212', currency: 'MAD', localities: ['Casablanca', 'Rabat', 'Marrakech', 'Fes', 'Tangier'] },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿', phone_code: '+258', currency: 'MZN', localities: ['Maputo', 'Matola', 'Beira', 'Nampula'] },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲', phone_code: '+95', currency: 'MMK', localities: ['Yangon', 'Mandalay', 'Naypyidaw'] },
  { code: 'NA', name: 'Namibia', flag: '🇳🇦', phone_code: '+264', currency: 'NAD', localities: ['Windhoek', 'Walvis Bay', 'Swakopmund'] },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷', phone_code: '+674', currency: 'AUD', localities: ['Yaren', 'Denigomodu'] },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵', phone_code: '+977', currency: 'NPR', localities: ['Kathmandu', 'Pokhara', 'Lalitpur'] },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱', phone_code: '+31', currency: 'EUR', localities: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht'] },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿', phone_code: '+64', currency: 'NZD', localities: ['Auckland', 'Wellington', 'Christchurch'] },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮', phone_code: '+505', currency: 'NIO', localities: ['Managua', 'Leon', 'Masaya'] },
  { code: 'NE', name: 'Niger', flag: '🇳🇪', phone_code: '+227', currency: 'XOF', localities: ['Niamey', 'Maradi', 'Zinder', 'Tahoua'] },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', phone_code: '+234', currency: 'NGN', localities: ['Lagos', 'Abuja', 'Kano', 'Ibadan', 'Port Harcourt'] },
  { code: 'MK', name: 'North Macedonia', flag: '🇲🇰', phone_code: '+389', currency: 'MKD', localities: ['Skopje', 'Bitola'] },
  { code: 'NO', name: 'Norway', flag: '🇳🇴', phone_code: '+47', currency: 'NOK', localities: ['Oslo', 'Bergen', 'Trondheim'] },
  { code: 'OM', name: 'Oman', flag: '🇴🇲', phone_code: '+968', currency: 'OMR', localities: ['Muscat', 'Salalah', 'Sohar'] },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', phone_code: '+92', currency: 'PKR', localities: ['Karachi', 'Lahore', 'Islamabad', 'Faisalabad'] },
  { code: 'PW', name: 'Palau', flag: '🇵🇼', phone_code: '+680', currency: 'USD', localities: ['Ngerulmud', 'Koror'] },
  { code: 'PA', name: 'Panama', flag: '🇵🇦', phone_code: '+507', currency: 'PAB', localities: ['Panama City', 'David', 'Colon'] },
  { code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬', phone_code: '+675', currency: 'PGK', localities: ['Port Moresby', 'Lae'] },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾', phone_code: '+595', currency: 'PYG', localities: ['Asuncion', 'Ciudad del Este'] },
  { code: 'PE', name: 'Peru', flag: '🇵🇪', phone_code: '+51', currency: 'PEN', localities: ['Lima', 'Arequipa', 'Trujillo'] },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', phone_code: '+63', currency: 'PHP', localities: ['Manila', 'Quezon City', 'Davao City', 'Cebu'] },
  { code: 'PL', name: 'Poland', flag: '🇵🇱', phone_code: '+48', currency: 'PLN', localities: ['Warsaw', 'Krakow', 'Gdansk'] },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', phone_code: '+351', currency: 'EUR', localities: ['Lisbon', 'Porto', 'Braga'] },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦', phone_code: '+974', currency: 'QAR', localities: ['Doha', 'Al Wakrah', 'Al Khor'] },
  { code: 'RO', name: 'Romania', flag: '🇷🇴', phone_code: '+40', currency: 'RON', localities: ['Bucharest', 'Cluj-Napoca', 'Timisoara'] },
  { code: 'RU', name: 'Russia', flag: '🇷🇺', phone_code: '+7', currency: 'RUB', localities: ['Moscow', 'Saint Petersburg', 'Novosibirsk'] },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼', phone_code: '+250', currency: 'RWF', localities: ['Kigali', 'Butare', 'Gisenyi', 'Gitarama'] },
  { code: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳', phone_code: '+1-869', currency: 'XCD', localities: ['Basseterre', 'Charlestown'] },
  { code: 'LC', name: 'Saint Lucia', flag: '🇱🇨', phone_code: '+1-758', currency: 'XCD', localities: ['Castries', 'Gros Islet'] },
  { code: 'VC', name: 'Saint Vincent', flag: '🇻🇨', phone_code: '+1-784', currency: 'XCD', localities: ['Kingstown'] },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸', phone_code: '+685', currency: 'WST', localities: ['Apia'] },
  { code: 'SM', name: 'San Marino', flag: '🇸🇲', phone_code: '+378', currency: 'EUR', localities: ['San Marino', 'Dogana'] },
  { code: 'ST', name: 'Sao Tome and Principe', flag: '🇸🇹', phone_code: '+239', currency: 'STN', localities: ['São Tomé', 'Trindade'] },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', phone_code: '+966', currency: 'SAR', localities: ['Riyadh', 'Jeddah', 'Mecca', 'Medina'] },
  { code: 'SN', name: 'Sénégal', flag: '🇸🇳', phone_code: '+221', currency: 'XOF', localities: ['Dakar', 'Thiès', 'Kaolack', 'Saint-Louis', 'Ziguinchor'] },
  { code: 'RS', name: 'Serbia', flag: '🇷🇸', phone_code: '+381', currency: 'RSD', localities: ['Belgrade', 'Novi Sad'] },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨', phone_code: '+248', currency: 'SCR', localities: ['Victoria', 'Anse Boileau'] },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱', phone_code: '+232', currency: 'SLE', localities: ['Freetown', 'Bo', 'Kenema', 'Makeni'] },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬', phone_code: '+65', currency: 'SGD', localities: ['Singapore'] },
  { code: 'SK', name: 'Slovakia', flag: '🇸🇰', phone_code: '+421', currency: 'EUR', localities: ['Bratislava', 'Kosice'] },
  { code: 'SI', name: 'Slovenia', flag: '🇸🇮', phone_code: '+386', currency: 'EUR', localities: ['Ljubljana', 'Maribor'] },
  { code: 'SB', name: 'Solomon Islands', flag: '🇸🇧', phone_code: '+677', currency: 'SBD', localities: ['Honiara'] },
  { code: 'SO', name: 'Somalia', flag: '🇸🇴', phone_code: '+252', currency: 'SOS', localities: ['Mogadishu', 'Hargeisa', 'Garowe'] },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦', phone_code: '+27', currency: 'ZAR', localities: ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria'] },
  { code: 'ES', name: 'Spain', flag: '🇪🇸', phone_code: '+34', currency: 'EUR', localities: ['Madrid', 'Barcelona', 'Valencia', 'Seville'] },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', phone_code: '+94', currency: 'LKR', localities: ['Colombo', 'Kandy', 'Galle'] },
  { code: 'SD', name: 'Sudan', flag: '🇸🇩', phone_code: '+249', currency: 'SDG', localities: ['Khartoum', 'Omdurman', 'Port Sudan'] },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷', phone_code: '+597', currency: 'SRD', localities: ['Paramaribo'] },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪', phone_code: '+46', currency: 'SEK', localities: ['Stockholm', 'Gothenburg', 'Malmo'] },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭', phone_code: '+41', currency: 'CHF', localities: ['Zurich', 'Geneva', 'Basel', 'Bern'] },
  { code: 'SY', name: 'Syria', flag: '🇸🇾', phone_code: '+963', currency: 'SYP', localities: ['Damascus', 'Aleppo', 'Homs'] },
  { code: 'TW', name: 'Taiwan', flag: '🇹🇼', phone_code: '+886', currency: 'TWD', localities: ['Taipei', 'Kaohsiung'] },
  { code: 'TJ', name: 'Tajikistan', flag: '🇹🇯', phone_code: '+992', currency: 'TJS', localities: ['Dushanbe', 'Khujand'] },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿', phone_code: '+255', currency: 'TZS', localities: ['Dar es Salaam', 'Dodoma', 'Mwanza', 'Arusha'] },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭', phone_code: '+66', currency: 'THB', localities: ['Bangkok', 'Chiang Mai', 'Phuket'] },
  { code: 'TG', name: 'Togo', flag: '🇹🇬', phone_code: '+228', currency: 'XOF', localities: ['Lomé', 'Sokodé', 'Kara', 'Atakpamé', 'Kpalimé'] },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴', phone_code: '+676', currency: 'TOP', localities: ['Nuku\'alofa'] },
  { code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹', phone_code: '+1-868', currency: 'TTD', localities: ['Port of Spain', 'Chaguanas'] },
  { code: 'TN', name: 'Tunisia', flag: '🇹🇳', phone_code: '+216', currency: 'TND', localities: ['Tunis', 'Sfax', 'Sousse'] },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷', phone_code: '+90', currency: 'TRY', localities: ['Istanbul', 'Ankara', 'Izmir'] },
  { code: 'TM', name: 'Turkmenistan', flag: '🇹🇲', phone_code: '+993', currency: 'TMT', localities: ['Ashgabat'] },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬', phone_code: '+256', currency: 'UGX', localities: ['Kampala', 'Entebbe', 'Gulu', 'Mbarara'] },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦', phone_code: '+380', currency: 'UAH', localities: ['Kyiv', 'Lviv', 'Odessa'] },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪', phone_code: '+971', currency: 'AED', localities: ['Dubai', 'Abu Dhabi', 'Sharjah'] },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', phone_code: '+44', currency: 'GBP', localities: ['London', 'Birmingham', 'Manchester', 'Glasgow'] },
  { code: 'US', name: 'United States', flag: '🇺🇸', phone_code: '+1', currency: 'USD', localities: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Miami'] },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾', phone_code: '+598', currency: 'UYU', localities: ['Montevideo'] },
  { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿', phone_code: '+998', currency: 'UZS', localities: ['Tashkent', 'Samarkand'] },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺', phone_code: '+678', currency: 'VUV', localities: ['Port Vila'] },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪', phone_code: '+58', currency: 'VES', localities: ['Caracas', 'Maracaibo'] },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳', phone_code: '+84', currency: 'VND', localities: ['Ho Chi Minh City', 'Hanoi', 'Da Nang'] },
  { code: 'YE', name: 'Yemen', flag: '🇾🇪', phone_code: '+967', currency: 'YER', localities: ['Sanaa', 'Aden'] },
  { code: 'ZM', name: 'Zambia', flag: '🇿🇲', phone_code: '+260', currency: 'ZMW', localities: ['Lusaka', 'Ndola', 'Kitwe', 'Livingstone'] },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', phone_code: '+263', currency: 'ZWG', localities: ['Harare', 'Bulawayo', 'Mutare', 'Gweru'] }
];
